version: '3'

volumes:
  postgres_data:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - HOST=0.0.0.0
      - PORT=4000
      - DATABASE_APP_URL=postgresql://postgres:postgres@database:5432/db?connect_timeout=300
    volumes:
      - ./apps/api/:/app/apps/api/
    command: npx nx run api:serve

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./apps/client/:/app/apps/client/
    command: npx nx run client:serve

  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

