version: '3'

networks:
  backend:
    external: true

volumes:
  postgres_data:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./node_modules:/app/node_modules
      #- ./apps/api/:/app/apps/api/
    command: npx nx run api:serve
    networks:
      - backend
  bunker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./node_modules:/app/node_modules
      #- ./apps/bunker/:/app/apps/bunker/
    command: npx nx run bunker:serve
    networks:
      - backend
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

