version: '3'

volumes:
  postgres_data:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./apps/api/:/app/apps/api/
    command: npx nx run api:serve

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./apps/client/:/app/apps/client/
    command: npx nx run client:serve

  database:
    image: postgres:14
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

